# Generated by Django 6.0.7 on 2026-09-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_contentview_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam"),
                    ("abuse", "Abuse"),
                    ("copyright", "Copyright"),
                    ("unsafe", "Unsafe content"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
